"""initial schema

Revision ID: 6dcc27a021cf
Revises: 
Create Date: 2026-07-26 15:47:15.489015

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dcc27a021cf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required by 02_DATABASE_SCHEMA.sql: uuid_generate_v4() server defaults
    # need uuid-ossp; idx_companies_name's gin_trgm_ops needs pg_trgm.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("employee_count_band", sa.String(length=50), nullable=True),
        sa.Column("revenue_band", sa.String(length=50), nullable=True),
        sa.Column("location_city", sa.String(length=255), nullable=True),
        sa.Column("location_state", sa.String(length=255), nullable=True),
        sa.Column(
            "location_country", sa.String(length=255), server_default=sa.text("'India'"), nullable=True
        ),
        sa.Column("incorporation_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column(
            "enrichment_status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "enrichment_status IN ('pending', 'enriched', 'failed')", name="companies_enrichment_status_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_companies_industry", "companies", ["industry"], unique=False)
    op.create_index(
        "idx_companies_name",
        "companies",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "crm_sync_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("direction IN ('push', 'pull')", name="crm_sync_log_direction_check"),
        sa.CheckConstraint("status IN ('success', 'failed', 'partial')", name="crm_sync_log_status_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('bd_executive', 'manager', 'admin')", name="users_role_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "crm_deals",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("deal_stage", sa.String(length=50), nullable=True),
        sa.Column("service_line", sa.String(length=50), nullable=True),
        sa.Column("deal_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("outcome IN ('won', 'lost', 'open')", name="crm_deals_outcome_check"),
        sa.CheckConstraint(
            "service_line IN ('branding', 'hiring', 'learning_development', 'iac_partnership')",
            name="crm_deals_service_line_check",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_crm_deals_company", "crm_deals", ["company_id"], unique=False)
    op.create_index("idx_crm_deals_outcome", "crm_deals", ["outcome"], unique=False)
    op.create_table(
        "lead_scores",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("fit_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("intent_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("conversion_probability", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("recommended_service", sa.String(length=50), nullable=True),
        sa.Column("recommendation_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("top_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "recommended_service IN ('branding', 'hiring', 'learning_development', 'iac_partnership')",
            name="lead_scores_recommended_service_check",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_lead_scores_company", "lead_scores", ["company_id"], unique=False)
    op.create_index(
        "idx_lead_scores_probability", "lead_scores", [sa.text("conversion_probability DESC")], unique=False
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("doc_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "doc_type IN ('job_posting', 'company_about', 'news_mention', 'press_release')",
            name="raw_documents_doc_type_check",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index("idx_raw_documents_company", "raw_documents", ["company_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("lead_score_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("is_accurate", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["lead_score_id"], ["lead_scores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nlp_features",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("raw_document_id", sa.UUID(), nullable=True),
        sa.Column("predicted_need_category", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("extracted_entities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "processed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "predicted_need_category IN ('branding', 'hiring', 'learning_development', 'iac_partnership')",
            name="nlp_features_predicted_need_category_check",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_document_id"], ["raw_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_nlp_features_company", "nlp_features", ["company_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_nlp_features_company", table_name="nlp_features")
    op.drop_table("nlp_features")
    op.drop_table("feedback")
    op.drop_index("idx_raw_documents_company", table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_index("idx_lead_scores_probability", table_name="lead_scores")
    op.drop_index("idx_lead_scores_company", table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index("idx_crm_deals_outcome", table_name="crm_deals")
    op.drop_index("idx_crm_deals_company", table_name="crm_deals")
    op.drop_table("crm_deals")
    op.drop_table("users")
    op.drop_table("crm_sync_log")
    op.drop_index(
        "idx_companies_name",
        table_name="companies",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("idx_companies_industry", table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
